name: Build and Deploy Docs

on:
  push:
    branches:
      - docs 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . # Installs the project in editable mode (using pyproject.toml).

    - name: Install Sphinx and Dependencies
      run: |
        pip install sphinx sphinx_rtd_theme   # Install Sphinx and the Read the Docs theme.

    - name: Build Docs
      run: |
        cd docs  # Wechsle ins Dokumentations-Verzeichnis
        sphinx-build -b html . _build/html  # Baue die HTML-Dokumentation

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main  # The branch to deploy the built docs to.
        folder: docs/_build/html
        token: ${{ secrets.GITHUB_TOKEN }}