name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - docs 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatchling  # Install hatchling explicitly
        pip install . # Installs the project in editable mode (using pyproject.toml).

    - name: Install Sphinx and Dependencies
      run: |
        pip install sphinx sphinx-book-theme   # Install Sphinx and the theme.

    - name: Build Docs
      run: |
        sphinx-build -b dirhtml docs/source . docs/_build/html

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main  # The branch to deploy the built docs to.
        folder: docs/_build/html
        token: ${{ secrets.GITHUB_TOKEN }}